name: develop deploy to firebase
'on':
  push:
    branches:
      - develop

jobs:
  deploy-develop:
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY_DEV }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: setup
        run: |
          echo $GCLOUD_SERVICE_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
          npm install -g firebase-tools
          firebase use develop

      - name: check functions changes
        id: diff_functions
        uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: |
            functions/**/*.ts
            functions/**/*.json

      - name: check firestore changes
        id: diff_firestore
        uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: |
            firestore.generate.rules
            firebase.indexes.json

      - name: check storage changes
        id: diff_storage
        uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: |
            storage.generate.rules

      - name: check hosting changes
        id: diff_hosting
        uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: |
            hosting/**/*

      - name: install firebase cli
        run: npm install -g firebase-tools

      - name: deploy functions
        run: |
          npm ci
          firebase deploy --only functions
        working-directory: ./functions
        if: steps.diff_functions.outputs.diff

      - name: deploy firestore
        run: firebase deploy --only firestore
        working-directory: ./firestore
        if: steps.diff_firestore.outputs.diff

      - name: deploy storage
        run: firebase deploy --only storage
        working-directory: ./storage
        if: steps.diff_storage.outputs.diff

      - name: deploy hosting
        run: firebase deploy --only hosting
        working-directory: ./hosting
        if: steps.diff_hosting.outputs.diff
