name: develop testing to firebase on emulator
'on':
  push:
    branches:
      - 'future/**'

jobs:
  testing-develop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install firebase cli
        run: npm install -g firebase-tools

      - name: set auth
        run: |
          touch service-account-file.json
          cat <<EOS > service-account-file.json
            ${{secrets.FIREBASE_AUTH_JSON_DEVELOP}}
          EOS
          export GOOGLE_APPLICATION_CREDENTIALS="service-account-file.json"

      - name: testing functions
        run: |
          firebase use develop
          firebase run test
        working-directory: ./functions

      - name: testing firestore
        run: |
          firebase use develop
          firebase run test
        working-directory: ./firestore

      - name: testing storage
        run: |
          firebase use develop
          firebase run test
        working-directory: ./storage
