name: develop testing to firebase on emulator
'on':
  push:
    branches:
      - 'future/**'

jobs:
  testing-develop:
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./service-account.json
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: setup
        run: |
          echo ${{ secrets.GCLOUD_SERVICE_KEY_DEV }} | base64 --decode > service-account.json
          npm install -g firebase-tools
          firebase use develop

      - name: testing functions
        run: |
          npm ci
          npm run test
        working-directory: ./functions

      - name: testing firestore
        run: |
          npm ci
          npm run test
        working-directory: ./firestore

      - name: testing storage
        run: |
          npm ci
          npm run test
        working-directory: ./storage

      - name: delete credentials
        run: rm $GOOGLE_APPLICATION_CREDENTIALS
        if: ${{ always() }}
