name: develop testing to firebase on emulator
'on':
  push:
    branches:
      - 'future/**'

jobs:
  testing-develop:
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./service-account.json
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY_DEV }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: setup
        run: |
          echo $GCLOUD_SERVICE_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
          npm install -g firebase-tools
          firebase use template-dev-a84f2

      - name: testing functions
        run: |
          echo $GCLOUD_SERVICE_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
          firebase use template-dev-a84f2
          npm ci
          npm run test
        working-directory: ./functions

      - name: testing firestore
        run: |
          npm ci
          npm run test
        working-directory: ./firestore

      - name: testing storage
        run: |
          npm ci
          npm run test
        working-directory: ./storage

      - name: delete credentials
        run: rm $GOOGLE_APPLICATION_CREDENTIALS
        if: ${{ always() }}
