name: develop testing to firebase on emulator
'on':
  push:
    branches:
      - 'develop/**'

steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v1
    with:
      node-version: ${{ matrix.node-version }}

  - name: install firebase cli
    run: npm install -g firebase-tools

  - name: testing functions
  - run: |
      firebase use staging --token ${{secrets.FIREBASE_TOKEN}}
      firebase run test
    working-directory: ./functions

  - name: testing firestore
  - run: |
      firebase use staging --token ${{secrets.FIREBASE_TOKEN}}
      firebase run test
    working-directory: ./firestore

  - name: testing storage
  - run: |
      firebase use staging --token ${{secrets.FIREBASE_TOKEN}}
      firebase run test
    working-directory: ./storage
