name: develop testing to firebase on emulator
'on':
  push:
    branches:
      - 'future/**'

jobs:
  testing-develop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: set auth
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{secrets.FIREBASE_AUTH_JSON_DEVELOP}}'

      - name: setup cli
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: testing functions
        run: |
          firebase use develop
          firebase run test
        working-directory: ./functions

      - name: testing firestore
        run: |
          firebase use develop
          firebase run test
        working-directory: ./firestore

      - name: testing storage
        run: |
          firebase use develop
          firebase run test
        working-directory: ./storage
