name: develop testing to firebase on emulator
'on':
  push:
    branches:
      - 'develop'

jobs:
  testing-staging:
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./service-account.json
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY_STG }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: setup
        run: |
          echo $GCLOUD_SERVICE_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
          npm install -g firebase-tools
          firebase use staging

      - name: testing functions
        run: npm run test
        working-directory: ./functions

      - name: testing firestore
        run: npm run test
        working-directory: ./firestore

      - name: testing storage
        run: npm run test
        working-directory: ./storage
